language: android

sudo:
  false

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer
  sonarqube:
    token:
      secure: "K8prSoYwfoKQGhJT2+tkilcYCqSRPqts/TLGkI+vyjgjB9tNJ6iJf610PzyO5dtCG/Y/deX6eh9TAWbJVPdFLzL5KY6nhaRu1WkLeK9lGTBtllxQMvH3WMMBYkl1QxgxP4TeSKqnnYbleKRTkE2mFcvZ4TQzHJZg8CcaBKDxwxTU39e21sXUle4rTcQyBgewu3D4cyIQ9PoqKJiSw5YWs56zyTHwU0NkJdKqpmXfNjf57KvoxtrXBnSX4Fj6CUwieusZIULCfQxXVv2Y64Optc3jGA1Zyf/UXFU5vpipPY13igCJxRgI0a5TbQ440+bgFb2+rBbZ/kq+QR3Qx2fQ4HQbV/fA1HHL0raRI21R5GuX3jx5+L1WPai4LYp+HRk7o0CrAngRIHM4mGFso3erxJoonlUXRR6L+uO3LRVqXWf0yVRjMN8dWoYrL2FDw744f4J/bfK4DauKcD/wmP58oRe9KhwbFhfaX0sPxknjrXl9LgOfiDme9HKvFY4Yg19h1vDdWHYZw95dzh1jQPqG/4z8+Gv1jv0dQv/W1oRbeVBjs2rnq3A86XWxaorR3lCSDH8JLn1qKPI/DYY/oAMqyF19fhfN5OtRpVNn18zsCoDMVI+0tw0SHtHbiR0LzgHED8kShJojJWKIQMWRs7afUo8LAYX/6d2+oHhqM6wBvQc="

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.2
    - android-25
    - extra-android-m2repository

before_script:
  - echo no | android create avd --force -n test -t android-18 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator

  # disable animations on CI device
  - adb shell settings put global window_animation_scale 0
  - adb shell settings put global transition_animation_scale 0
  - adb shell settings put global animator_duration_scale 0

  # unlock device
  - adb shell input keyevent 82

branches:
  only:
  - master
  - develop

script:
  bash ci.sh

after_script:
  ./gradlew sonarqube

env:
  global:
    - secure: "Gkd78BiNlkvJc2wSl+/Utm8l2jwhm5yJDiQgTA4UI3VRgKR49wvtcNWpedjKJKhJhjwZg18d1ASM1Yj1r1T4920uDWxbVkb9jIdyU+mY30/NCYJ+Sc+cHeiZVSV1RZdXe744cRBXsKoGnaOecBTQBQP0FRtwtw68nPVGFrwNxwOJPGLB8ScdHa4AIXwp0MUNaJMPNc08KihkNtouZr2MZaqWZPU7jMaTGTkaYZpOEMr1+MjYuW7IyD4lbp7fK0CL9l95y2bDZszoeg/zq27br0A0ijxx1ZBrYVQBpPIElnDNZLoS4gMGTxxwyk+0gKQXfyZQxc5GU5CIAvupt2DQbVTxOpcU0qQ8Oufx7lDQGTM+4Ghoxyp631WcO0R1RWUOlhrhyVe5SBm6rgKahyN+/UB3JEkAXcqqDTP7Kqz/7VUd4RGcN369/j40BANald7//y1KREtLLHNxbMWn/to9hlht9KzQoq4QNaLc9sKZRSCuyhrcfmRyrbbw8cRBxj1mdWVV/V/75nKL9+9u+/uXFhsLuLCjTgxEux+R0Fe/WCEuIV85kyaPwhsNbc0aCF90B2IQgKf8Vx3lEzTvje448dj3yYFd4PCLWEbBsC8NQWYUXjSTZKS+jjEELLsctM7mdBkQkxyPCTRQqeO4Pzl8tfHfa6GZdhJE6cXOs72sl0M="

notifications:
  slack:
    secure: "UIdgmgulJ5+wXf9zWQLk+8UzCrdqJTXZ6ysL/IsyRElNinJFbJr2PD2qAy9QR4sacNK6q9sTHcUD9RceBLYOJ5nLJpwt1I4vQy7Sd/1TaJqOohKIBY4f5ntpjrNs2DE9NO2qSc6nrFu5QDVCY+7dVaYEsurkyQeExC+0h+SrAxPUDOE8/UQ+lls8idQ/RCvw3/Tcr/i7r+JAV9ICH1xtIz7nydu7nzczYiILmlf+1rylGjo8omJDnl5P0SHyE7i1jLqgwheJh/ebLDFCavjDBNTQP3kjJGKf4gWXuvn85wGsIGqkdBc8YRpU3mOPnllucSSI78iDyVKEN6c/Em+lcCIJhKmsqBNoSq4ZsCLTu3XXJd001WalFv4+Iq/7v9P1HYqHw5A3R9N01XSd3RFF7MUh5iUSoBDxbusgqQ4en+sWgpD72K2GEdGUiEGu+6qj6AW/uho2+gyev5KzYV8NZenLy0hZ4Hkc6R3ofGB1v7IwxMj3UT8+V82oOwzZCWQyzEQvuvE7RZxXc6vgENkFUnveEOqk/YlAZLUFzjV0QSQRUyS5ZeTmNV0x8ozTH1/NU50jJRVyYBxOm5yBpDEVzqopdVDoMBNAJxtg8vGHMtrN5XliaBy6Aq7Gcr5V1woQjhJFjUmV7PaElxnaSPfYo3fwPL4oKSzTEJfyHc8wVWU="
  email: true

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle
    - $HOME/.sonar/cache
